### ISSUE TITLE
Sensor solat di waktu hadapan

### ISSUE THREAD

**Issue by aminbp** [zubir2k/HomeAssistantAdzan#1]
Saya ingin membuat kiraan waktu untuk trigger event untuk solat waktu akan datang, contoh sensor.solat_sekarang hanya boleh di trigger bila masuk waktu solat. Saya bercadang untuk buat trigger alarm 30 minit sebelum masuk waktu solat akan datang untuk bersiap untuk solat. Boleh ke tuan tambah sensor.solat_akandatang ?

**Comment by ajimaxman** [comment]
Idea yang bernas.

**Comment by zubir2k** [comment]
Boleh saje dilakukan pada automation.. menggunakan trigger by template. Sbg contoh dibawah
`{{state_attr("sensor.esolat_maghrib", "24hours") == (as_local(now()).strftime("%s") | int + (25*60)) | timestamp_custom("%H:%M", false)}}`

template ini akan trigger apabila tiba waktu 25minit (mengikut value pada `int + (25*60)`) sebelum waktu solat maghrib. Sbg contoh penggunaan, saya laungkan surah pilihan secara random seperti yang saya kongsikan pada README (keyword: random verse).

contoh automation saya akan kongsikan juga diruang [automation.yaml](/zubir2k/HomeAssistantAdzan/blob/main/automation.yaml)
