### ISSUE TITLE
Publish to HACS

### ISSUE THREAD

**Issue by thewan056** [zubir2k/HomeAssistantAdzan#3]
Please publish your work to hacs
https://hacs.xyz/
I had to search using google and github search engine to find your project, which is annoying. (In other words, sangat leceh)
By publishing to HACS you will get better discovery and easy installation, management and updates for the end user as i will always search HACS first when I want to add something to my Home Assistant. I already manually added the Jakim API to my own HA setup and created my own sensors and automations, so I don't need to use your addon anymore but it was a lot of work. If only I found your addon earlier I would have saved a lot of time testing and troubleshooting.
Not everyone in Malaysia uses Facebook, so i can't get my information from other Malaysians.

**Comment by zubir2k** [comment]
Salam,

Thank you for your feedback. As you've pointed to publish at HACS for discovery and installation, unfortunately it will unlikely to happened as this is not a custom integration addon. **It is a YAML template that heavily uses Jinja and I have made it so it is very easy to install (with zero changes required to the template YAML)**. I'm sure you're able to tell the differences 😉

I can assure you that this ~addon~ template is not just published on [Facebook](https://www.facebook.com/groups/homeassistantmalaysia/permalink/463318745624497), but also to other social media such as ~twitter~ [X](https://x.com/zubirjamal) as well as video guide on [YouTube](https://youtu.be/SVzybCpjWGQ). Some even reached out on [Instagram](https://instagram.com/zubirjamal.official) (non-Malaysians) to seek guidance on how to use the template. We also have a telegram group should you consider joining ~ [HA Malaysia](https://t.me/HAssMalaysia)

Perhaps if you insist in using HACS, I have published an AppDaemon App there. But it will not include automations or media player selections etc. Only prayer time sensors that are automatically created based on all available person entities in your HA. It will change the prayer time according to the GPS location of the person (as long as it is still within Malaysia). 

If you keen to try, add this as your custom repo in HACS **[zubir2k/HomeAssistantEsolatGPS](https://zubirco.de/HomeAssistantEsolatGPS)**

Thanks again for your time and may this template be beneficial to those who find it useful. Insha'Allah.
