### ISSUE TITLE
Sensors state turn unavailable after some time

### ISSUE THREAD

**Issue by hzq23x** [zubir2k/HomeAssistantAdzan#4]
Happened multiple times within last year, always after restart or update. refresh doesn't work, reinput state code doesn't work, change sources doesn't work.

**Comment by zubir2k** [comment]
Salam

Thanks for the feedback.

Thats quite odd considering the template fetches the data from Jakim every 30sec.

Perhaps you could provide a little bit more detail such as sensor name, and during what time it turned to 'unavailable' 

Also consider using local source as it store the solat data locally into your HA and reduce the reliance on Jakim API. If selecting local did not work, try run the 'Yearly Update' automation.

Hope this helps.

Thanks

**Comment by hzq23x** [comment]
Wslm.

Actually now it resolved randomly without restart/automation

it affects all the waktu solat sensor and hijri date. Usually happens after HA update and would last few days, happening for maybe over a year since first install

Tried switch to local + yearly refresh, still unavailable. Also tried clean reinstall, no change

local source actually hasn't worked since first install. followed all instruction on video and also on the github for install

**Comment by hzq23x** [comment]
![Screenshot 2024-09-16 172958](https://github.com/user-attachments/assets/fced823e-7d05-49aa-8f65-fc691feba3c8)

as shown here, turns unavailable at random times, without any change to config or HA and doesn't fix with manual control refresh or yearly update/startup refresh automation

**Comment by hzq23x** [comment]
could be API issue on jakim end? esolat website is currently down

**Comment by hzq23x** [comment]
![image](https://github.com/user-attachments/assets/47dbabff-3c46-43af-b0b3-d02f2084be64)

yup, it is probably server side issue. will close issue. do reach out if possible if there is any alternative solution
